Repository looseendsproject/webapp, pull requests merged in 2025-02, with the labels that each got.

#48 Fix "Uncaught TypeError" in the JS console.
  DEVELOPERS.md
  app/javascript/controllers/index.js
  app/javascript/controllers/project_form_controller.js
  app/javascript/controllers/toggle_status_controller.js
  app/views/layouts/_address_form.html.haml
  app/views/manage/projects/_form.html.haml
  app/views/manage/projects/index.html.haml
Labels: Bug

#56 Remove project_id requirements for finisher autocomplete.
  app/views/manage/projects/_form.html.haml
  config/routes.rb
Labels: Bug

#61 Overcommit git tooling
  .github/dependabot.yml
  .overcommit.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  README.md
Labels: Infrastructure

#55 Make inputs on sign up screen reader accessible
  app/views/devise/registrations/new.html.haml
Labels: Enhancement

#54 capture pgdump from prod periodically
  .gitignore
Labels: Infrastructure

#57 Set up staging environment (2nd attempt)
  .env.sample
  .gitignore
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  app/views/layouts/application.html.haml
Labels: Infrastructure

#58 Add tests for manage finishers and projects controllers
  app/controllers/manage/finishers_controller.rb
  app/controllers/manage/projects_controller.rb
  config/initializers/geocoder.rb
  test/controllers/manage/finishers_controller_test.rb
  test/controllers/manage/projects_controller_test.rb
  test/test_helper.rb
Labels: Infrastructure

#59 Dockerfiles
  Dockerfile
  Gemfile.lock
  docker-compose.yml
Labels: Infrastructure
